
		/// <reference types="cypress" />

		context('Generated By Ctflow', () => {
      it('Demo CtFlow 0', () => {
            
      cy.visit('https://neo4j.com/')
    

      cy.wait(15000)
    

      cy.get('#n-solutions-menu').click()
    

      cy.get('#n-solutions-menu > .text-charcoal').click()
    

      cy.get('.menu-item-wrapper > [href="/use-cases/"]').click()
    

          })
		})
		