
		/// <reference types="cypress" />

		context('Generated By Ctflow', () => {
			it('Demo CtFlow', () => {
				
      cy.visit('https://mystorage.coderclient.com/booking/')
    

    cy.get('.ant-input').type('1')
    

      cy.get('.space-input > .container > .ant-col > .ant-btn').click()
    

      cy.get(':nth-child(3) > :nth-child(1) > .ant-btn').click()
    

      cy.get('.ant-row > :nth-child(2) > .ant-btn').click()
    

      cy.get('.SpaceCardElements__HorizontalSpacesItemName-sc-1q3cuc8-14').contains("Shelf Space | No AC")
    

      cy.get(':nth-child(4) > .ant-row-end > .ant-col-sm-18 > .ant-btn').click()
    

      cy.get('.Text__TitlePage-sc-pipv5l-0').contains("What Services would you like to use?")
    

      cy.get('.MobileFooter_mobileFooter__8bGF7 :nth-child(2) > .ant-btn').click()
    

      cy.get(':nth-child(1) > .column--pricing').contains("439,120 VND")
    

      cy.get('.ant-col-14').contains("439,120 VND/month")
    

    cy.get('.ant-picker').type('28-02-2023')
    

      cy.get('td[title="2023-02-20"]').click()
    

      cy.wait(1000)
    

      cy.get('#rc_select_0').click()
    

      cy.wait(1000)
    

      cy.get('[title="10:00 AM - 10:59 AM"] > .ant-select-item-option-content').click()
    

      cy.get(':nth-child(2) > .ant-btn').click()
    

    cy.get('#name').type('Testing')
    

    cy.get('#phone').type('12345679')
    

    cy.get('#email').type('test@gmail.com')
    

      cy.get('.ant-row > :nth-child(2) > .ant-btn').click()
    

      cy.get('.Text__TitlePage-sc-pipv5l-0 > span').contains("Please review your booking")
    

      cy.get(':nth-child(2) > :nth-child(2) > .label--value').contains("Testing")
    

      cy.get(':nth-child(3) > .label--value').contains("12345679")
    

      cy.get(':nth-child(4) > .label--value').contains("test@gmail.com")
    

			})
		})
		