
		/// <reference types="cypress" />

		context('Generated By Ctflow', () => {
      it('Demo CtFlow 0', () => {
            
      cy.visit('https://vnexpress.net')
    

      cy.get('html').contains("vnexpress.net")
    

          })
		})
		